import os

from google import genai
from pydantic import BaseModel, Field
from typing import List
from dotenv import load_dotenv

load_dotenv(verbose=True)


class EnvironmentalFutureCommitments(BaseModel):
    year: int = Field(description="The year that the company aims to achieve the given target")
    value: int = Field(description="The percentage or value of the target set to use the given environmentally-friendly quantity.")

class SocialStandards(BaseModel):
    criterion: str = Field(description="Social element of the operations of the company")
    comment: str = Field(description="Statistic of the social factor above")

class GovernanceStandards(BaseModel):
    criterion: str = Field(description="Governance element of the operations of the company")
    comment: str = Field(description="Statistic of the governance factor above")

class EnvironmentalQuantityValue(BaseModel):
    name: str = Field(description="The name of any commodity or measurable quantity.")
    value: int = Field(description="The percentage or value of environmentally-friendly usage of the quantity.")
    future: List[EnvironmentalFutureCommitments] = Field(description="A list of the commitments made for the future that aim to increase the environmentally friendly usage of the quantity")
    unit: str = Field(description="The unit of measurement that was used for the quantity.")

class Company(BaseModel):
    company_name: str = Field(description="The name of the company by which it is commonly referred to, without any abbreviations.")
    company_slug: str = Field(description="The slug generated by concatenating the individual words in the company's full name, with hyphens. Always use regular hyphens.")
    company_type: str = Field(description="The industry that the company operates in.")
    company_year: int = Field(description="The year of the report for the given company.")
    environmental_quantities: List[EnvironmentalQuantityValue] = Field(description="A list of the environmentally-friendly commodities or emissions used by the company.")
    social_elements: List[SocialStandards] = Field(description="A list of the social factors discussed in the report, and their progress")
    governance_elements: List[GovernanceStandards] = Field(description="A list of the governance factors discussed in the report and their progress")


def extract_data(path_to_context_file: str):
    # Step 1: read the context file
    with open(path_to_context_file, "r", encoding='utf-8') as f:
        data = f.read()

    # Step 2: instantiate model client and prompt
    model_client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

    prompt = """
    Please extract the values of commodities or emissions (Scope 1, Scope 2, etc) that are targets for reduction in usage
    to reduce environmental harm, from the below context. Remove all mathematical english.
    Also extract social and governance data if present, for the given report.
    Since this data will be used in a database to track commitments, please use common English names and reduce all mentions of a common mineral, element or compound to one aggregated value. 
    Any specific products used by the company must not be mentioned in the output, as we need to **compare values across years**, and adding names in causes issues with comparison.
    
    The "company_type" field must have one of the following string values:
    1. Technology
    2. Consumer Discretionary
    3. Energy
    4. Communication Services
    5. Automotive
    6. Healthcare
    7. Financials
    8. Consumer Staples
    9. Industrials
    10. Materials
    11. Utilities
    12. Oil & Gas / Diversified
    13. Banking
    14. Telecom
    15. IT Services
    16. Financial Services
    17. Construction
    18. FMCG
    19. Automobile
    20. Auto / Farm
    21. Pharmaceuticals
    22. Cement
    23. Power
    24. Oil & Gas
    25. Steel
    """ + data

    # Step 3: generate response
    response = model_client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt,
        config={
            "response_mime_type": "application/json",
            "response_json_schema": Company.model_json_schema(),
        }
    )

    company_content = Company.model_validate_json(response.text)
    return company_content

if __name__ == "__main__":
    company_content = extract_data("../out/llm_context.txt")
    print(company_content)