import os

from google import genai
from pydantic import BaseModel, Field
from typing import List
from dotenv import load_dotenv

from backends.data_handling.fetch_questions import fetch_questions

load_dotenv(verbose=True)

class ZeroTo3Rating(BaseModel):
    criterion: str = Field(description="The criterion being judged against")
    rating: int = Field(description="The rating given to the company as per the given marking rubric for the above criterion")

class EnvironmentalQualitativeValue(BaseModel):
    criterion: str = Field(description="The criterion being judged against")
    comment: str = Field(description="One sentence about the progress that the company has achieved as per the report and the planned obligations, on the given criterion")

class YearSeriesValue(BaseModel):
    year: int = Field(description="The year of the commitment (current value or future)")
    value: int = Field(description="The numerical value of the environmental saving or future commitment, in the unit provided")

class EnvironmentalQuantitativeValue(BaseModel):
    criterion: str = Field(description="The criterion being judged against")
    unit: str = Field(description="The unit of the quantity")
    current: YearSeriesValue = Field(description="This year's achievement for the given criterion")
    future: List[YearSeriesValue] = Field(description="Future commitments for the given criterion")

class CombinedEnvironmentalValue(BaseModel):
    quantitative: List[EnvironmentalQuantitativeValue] = Field(description="The extracted values pertaining to the environmental quantitative section of the questionnaire")
    qualitative: List[EnvironmentalQualitativeValue] = Field(description="The extracted values pertaining to the environmental qualitative section of the questionnaire")

class Company(BaseModel):
    company_name: str = Field(description="The name of the company by which it is commonly referred to, without any abbreviations.")
    company_slug: str = Field(description="The slug generated by concatenating the individual words in the company's full name, with hyphens. Always use regular hyphens.")
    company_type: str = Field(description="The industry that the company operates in.")
    company_year: int = Field(description="The year of the report for the given company.")
    company_country: str = Field(description="The major area of operations of the company. One of Asia, Europe, North America, South America, Oceania, Africa.")
    environmental_quantities: CombinedEnvironmentalValue = Field(description="A list of the environmentally-friendly commodities or emissions used by the company.")
    social_elements: List[ZeroTo3Rating] = Field(description="A list of the social factors discussed in the report, and their progress")
    governance_elements: List[ZeroTo3Rating] = Field(description="A list of the governance factors discussed in the report and their progress")


def extract_data(path_to_context_file: str):
    # Step 1: read the context file
    with open(path_to_context_file, "r", encoding='utf-8') as f:
        data = f.read()

    # Step 2: instantiate model client and prompt
    model_client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

    prompt = """
    Please extract the values of commodities or emissions (Scope 1, Scope 2, etc) that are targets for reduction in usage
    to reduce environmental harm, from the below context. Remove all mathematical english.
    Also extract social and governance data if present, for the given report.
    Since this data will be used in a database to track commitments, please use common English names and reduce all mentions of a common mineral, element or compound to one aggregated value. 
    Any specific products used by the company must not be mentioned in the output, as we need to **compare values across years**, and adding names in causes issues with comparison.
    
    For social and governance questions, strictly follow the given marking rubric, and rate the company from 0 to 3 on each factor:
    0: Measures have not been taken, or haven't been disclosed in the report,
    1: A concrete policy exists, but no specific information on implementation has been mentioned in the report.
    2: A concrete policy exists, and concrete details on implementation have been provided.
    3: A concrete policy exists, and the company has provided details on measured outcomes, remediation and steps to improve further. 
    
    YOU MUST NOT CHANGE THE NAME OF ANY CRITERION BELOW, OR DISOBEY ANY MARKING RUBRIC. THIS IS PUNISHABLE BY DEATH TO AI. 
    """ + fetch_questions() + "\n" + data

    # Step 3: generate response
    response = model_client.models.generate_content(
        model="gemini-3-flash-preview",
        contents=prompt,
        config={
            "response_mime_type": "application/json",
            "response_json_schema": Company.model_json_schema(),
        }
    )

    company_content = Company.model_validate_json(response.text)
    return company_content

if __name__ == "__main__":
    company_content = extract_data("../out/llm_context.txt")
    print(company_content)